language: python

python:
  - "3.7"
  - "3.8"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER dev;" -U postgres

script:
  - python3 manage.py test
