language: python

python:
  - "3.7"
  - "3.8"

env:
  - DJANGO="3.0.3"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -c "CREATE USER dev;" -U postgres
  - psql -c "ALTER USER dev CREATEDB;" -U postgres
  - psql -c "ALTER DATABASE travis_ci_test OWNER TO dev;" -U postgres

script:
  - python3 manage.py test
