# Generated by Django 3.0.3 on 2020-04-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200405_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(max_length=2000)
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.CharField(max_length=2000)
        ),
    ]
