# Generated by Django 3.0.3 on 2020-04-06 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200406_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMuscleGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Activity')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MuscleGroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='muscle_groups'
        ),
        migrations.AddField(
            model_name='activity',
            name='muscle_groups',
            field=models.ManyToManyField(through='api.ActivityMuscleGroups', to='api.MuscleGroup'),
        ),
    ]
