# Generated by Django 3.0.3 on 2020-04-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200406_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserActivity',
            new_name='ScheduledActivity',
        ),
    ]
