# Generated by Django 3.0.3 on 2020-04-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200415_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledactivity',
            name='date',
            field=models.CharField(default='yyyymmdd', max_length=8),
        ),
    ]
