# Generated by Django 3.0.3 on 2020-04-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200415_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledactivity',
            name='date',
            field=models.CharField(default='yyyy-mm-dd', max_length=10),
        ),
    ]
